name: Pipeline Principal

on:
  push:
    branches:
      - master

jobs:

  hello:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
      - name: Say Goodbye
        run: echo "Goodbye"
