name: Pipeline Principal

on:
  push:
    branches:
      - master

jobs:

  environment-variables-print:
    name: "Print Person Name"
    runs-on: ubuntu-latest
    env:
      NAME: ${{secrets.name}}
      WORLD: "Earth"
    steps:
      - name: Print Hello {{Person(Variable)}}
        run: echo Hello $NAME !, Welcome to $WORLD 

  build:
    name: "Build Project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: npm run build ./backend

  # test:
  #   name: "Tests"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Show the directory
  #       run: cd backend
  #     - name: Install Node
  #       run: npm install
  #     - name: Run Tests
  #       run: npm run test
      
