name: Pipeline Principal

on:
  push:
    branches:
      - master

jobs:

  hello:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat backend/index.ts
