name: Pipeline Principal

on:
  push:
    branches:
      - master

jobs:

  hello:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat backend/index.ts
      - name: Move to backend folder
        run: cd backend
      - name: Install Node
        run: npm install

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Move to backend folder
        run: cd backend
      - name: Run Tests
        run: npm run teste
      
